### PR TITLE
Merge upstream and ver 3.2.0

### PR DESCRIPTION
**Pull request by johanhugg**
MTC2-1239

### CODE REVIEW

**Review by bomehlsen — APPROVED** [review]
lgtm - but wouldn't it be better to use the same version number as Adyen? At least major and minor version?

**Comment by johanhugg** [comment]
i see no issue with keeping it the same as them really. i've always just winged it hehe.

**Comment by johanhugg** [comment]
Had to update patch because 2.2.0 is what is currently used in adyen-service :)

**Comment by bomehlsen** [comment]
> Had to update patch because 2.2.0 is what is currently used in adyen-service :)

But isn't their version 3.2.0?

**Comment by johanhugg** [comment]
> > Had to update patch because 2.2.0 is what is currently used in adyen-service :)
> 
> But isn't their version 3.2.0?

Ops, you're right :)

**Review by bomehlsen — APPROVED** [review]
Go for it!

**Pull request merged**
